version: '3.9'

services:
  postgres:
    image: postgres:17.2
    container_name: postgres_user_subscription
    environment:
      POSTGRES_DB: user_subscription
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ~/pgdata:/var/lib/postgresql/data/pgdata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql