version: '3.9'

services:
  postgres:
    image: postgres:17.2
    container_name: postgres_user_subscription
    environment:
      POSTGRES_DB: user_subscription
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ~/pgdata:/var/lib/postgresql/data/pgdata

  app:
    build: ..
    container_name: user_subscription
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: user_subscription
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network: