spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # В Проде схему лучше не накатывать через hibernate (лучше через liquibase/flyway, подконтрольно), но для упрощения пока что сделал так.
    hibernate.ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: httptrace
  httptrace:
    maximum: 1000
  httpexchanges:
    recording:
      # Нет смысла дописывать логи в каждом методе каждого контроллера,
      # когда можем сразу логировать все запросы одной строкой в конфиге через актуатор
      include: REQUEST_HEADERS,REMOTE_ADDRESS,COOKIE_HEADERS,AUTHORIZATION_HEADER,RESPONSE_HEADERS,PRINCIPAL,SESSION_ID,TIME_TAKEN